//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReferenceRuleSegmentManager {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SegmentType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
        "egmentStudio.Model")]
    public enum SegmentType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RuleSegment = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TaxonomySegment = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MixedSegment = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PMSegment = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SegmentBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
        "egmentStudio.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.RuleSegment))]
    public partial class SegmentBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string HitLogicRefIdk__BackingFieldField;
        
        private bool IsSandboxSegmentk__BackingFieldField;
        
        private System.Collections.Generic.Dictionary<string, string> PropertyPackk__BackingFieldField;
        
        private int authoringSegmentIdField;
        
        private string commentField;
        
        private string countryField;
        
        private System.DateTime createTimeField;
        
        private ConsoleApplication1.ServiceReferenceRuleSegmentManager.ComputeStatus currentStatusField;
        
        private string descriptionField;
        
        private System.Nullable<System.DateTime> lastModifiedTimeField;
        
        private string ownerIdField;
        
        private string projectIdField;
        
        private ConsoleApplication1.ServiceReferenceRuleSegmentManager.PublishStatus publishStatusField;
        
        private string segmentIdField;
        
        private string segmentNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<HitLogicRefId>k__BackingField", IsRequired=true)]
        public string HitLogicRefIdk__BackingField {
            get {
                return this.HitLogicRefIdk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.HitLogicRefIdk__BackingFieldField, value) != true)) {
                    this.HitLogicRefIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("HitLogicRefIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IsSandboxSegment>k__BackingField", IsRequired=true)]
        public bool IsSandboxSegmentk__BackingField {
            get {
                return this.IsSandboxSegmentk__BackingFieldField;
            }
            set {
                if ((this.IsSandboxSegmentk__BackingFieldField.Equals(value) != true)) {
                    this.IsSandboxSegmentk__BackingFieldField = value;
                    this.RaisePropertyChanged("IsSandboxSegmentk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PropertyPack>k__BackingField", IsRequired=true)]
        public System.Collections.Generic.Dictionary<string, string> PropertyPackk__BackingField {
            get {
                return this.PropertyPackk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyPackk__BackingFieldField, value) != true)) {
                    this.PropertyPackk__BackingFieldField = value;
                    this.RaisePropertyChanged("PropertyPackk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int authoringSegmentId {
            get {
                return this.authoringSegmentIdField;
            }
            set {
                if ((this.authoringSegmentIdField.Equals(value) != true)) {
                    this.authoringSegmentIdField = value;
                    this.RaisePropertyChanged("authoringSegmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                if ((object.ReferenceEquals(this.commentField, value) != true)) {
                    this.commentField = value;
                    this.RaisePropertyChanged("comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                if ((object.ReferenceEquals(this.countryField, value) != true)) {
                    this.countryField = value;
                    this.RaisePropertyChanged("country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime createTime {
            get {
                return this.createTimeField;
            }
            set {
                if ((this.createTimeField.Equals(value) != true)) {
                    this.createTimeField = value;
                    this.RaisePropertyChanged("createTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ConsoleApplication1.ServiceReferenceRuleSegmentManager.ComputeStatus currentStatus {
            get {
                return this.currentStatusField;
            }
            set {
                if ((this.currentStatusField.Equals(value) != true)) {
                    this.currentStatusField = value;
                    this.RaisePropertyChanged("currentStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> lastModifiedTime {
            get {
                return this.lastModifiedTimeField;
            }
            set {
                if ((this.lastModifiedTimeField.Equals(value) != true)) {
                    this.lastModifiedTimeField = value;
                    this.RaisePropertyChanged("lastModifiedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ownerId {
            get {
                return this.ownerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ownerIdField, value) != true)) {
                    this.ownerIdField = value;
                    this.RaisePropertyChanged("ownerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string projectId {
            get {
                return this.projectIdField;
            }
            set {
                if ((object.ReferenceEquals(this.projectIdField, value) != true)) {
                    this.projectIdField = value;
                    this.RaisePropertyChanged("projectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ConsoleApplication1.ServiceReferenceRuleSegmentManager.PublishStatus publishStatus {
            get {
                return this.publishStatusField;
            }
            set {
                if ((this.publishStatusField.Equals(value) != true)) {
                    this.publishStatusField = value;
                    this.RaisePropertyChanged("publishStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string segmentId {
            get {
                return this.segmentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.segmentIdField, value) != true)) {
                    this.segmentIdField = value;
                    this.RaisePropertyChanged("segmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string segmentName {
            get {
                return this.segmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.segmentNameField, value) != true)) {
                    this.segmentNameField = value;
                    this.RaisePropertyChanged("segmentName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RuleSegment", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
        "egmentStudio.Model")]
    [System.SerializableAttribute()]
    public partial class RuleSegment : ConsoleApplication1.ServiceReferenceRuleSegmentManager.SegmentBase {
        
        private System.Nullable<System.DateTime> computeActionTimeField;
        
        private string expirationTimeField;
        
        private ConsoleApplication1.ServiceReferenceRuleSegmentManager.SegmentExpirationTimeFrameType expirationTimeTypeField;
        
        private string fullExpressionField;
        
        private ConsoleApplication1.ServiceReferenceRuleSegmentManager.SegmentRule[] rulesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> computeActionTime {
            get {
                return this.computeActionTimeField;
            }
            set {
                if ((this.computeActionTimeField.Equals(value) != true)) {
                    this.computeActionTimeField = value;
                    this.RaisePropertyChanged("computeActionTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string expirationTime {
            get {
                return this.expirationTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.expirationTimeField, value) != true)) {
                    this.expirationTimeField = value;
                    this.RaisePropertyChanged("expirationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ConsoleApplication1.ServiceReferenceRuleSegmentManager.SegmentExpirationTimeFrameType expirationTimeType {
            get {
                return this.expirationTimeTypeField;
            }
            set {
                if ((this.expirationTimeTypeField.Equals(value) != true)) {
                    this.expirationTimeTypeField = value;
                    this.RaisePropertyChanged("expirationTimeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string fullExpression {
            get {
                return this.fullExpressionField;
            }
            set {
                if ((object.ReferenceEquals(this.fullExpressionField, value) != true)) {
                    this.fullExpressionField = value;
                    this.RaisePropertyChanged("fullExpression");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ConsoleApplication1.ServiceReferenceRuleSegmentManager.SegmentRule[] rules {
            get {
                return this.rulesField;
            }
            set {
                if ((object.ReferenceEquals(this.rulesField, value) != true)) {
                    this.rulesField = value;
                    this.RaisePropertyChanged("rules");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComputeStatus", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
        "egmentStudio.Model")]
    public enum ComputeStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotComputed = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Running = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Computed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PublishStatus", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
        "egmentStudio.Model")]
    public enum PublishStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotPublished = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PublishSuccessfully = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PublishUnsuccessfully = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SegmentExpirationTimeFrameType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
        "egmentStudio.Model")]
    public enum SegmentExpirationTimeFrameType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hour = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Day = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SegmentRule", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
        "egmentStudio.Model")]
    [System.SerializableAttribute()]
    public partial class SegmentRule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ConsoleApplication1.ServiceReferenceRuleSegmentManager.RuleConstraint[] constraintsField;
        
        private int indexNoField;
        
        private string ruleIdField;
        
        private ConsoleApplication1.ServiceReferenceRuleSegmentManager.RuleType ruleTypeField;
        
        private string segmentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ConsoleApplication1.ServiceReferenceRuleSegmentManager.RuleConstraint[] constraints {
            get {
                return this.constraintsField;
            }
            set {
                if ((object.ReferenceEquals(this.constraintsField, value) != true)) {
                    this.constraintsField = value;
                    this.RaisePropertyChanged("constraints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int indexNo {
            get {
                return this.indexNoField;
            }
            set {
                if ((this.indexNoField.Equals(value) != true)) {
                    this.indexNoField = value;
                    this.RaisePropertyChanged("indexNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ruleId {
            get {
                return this.ruleIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ruleIdField, value) != true)) {
                    this.ruleIdField = value;
                    this.RaisePropertyChanged("ruleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ConsoleApplication1.ServiceReferenceRuleSegmentManager.RuleType ruleType {
            get {
                return this.ruleTypeField;
            }
            set {
                if ((this.ruleTypeField.Equals(value) != true)) {
                    this.ruleTypeField = value;
                    this.RaisePropertyChanged("ruleType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string segmentId {
            get {
                return this.segmentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.segmentIdField, value) != true)) {
                    this.segmentIdField = value;
                    this.RaisePropertyChanged("segmentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RuleConstraint", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
        "egmentStudio.Model")]
    [System.SerializableAttribute()]
    public partial class RuleConstraint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string constraintIdField;
        
        private string constraintValueField;
        
        private ConsoleApplication1.ServiceReferenceRuleSegmentManager.RuleAttributeDataType dataTypeField;
        
        private ConsoleApplication1.ServiceReferenceRuleSegmentManager.ConstraintExpression[] expressionsField;
        
        private int indexNoField;
        
        private string ruleIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string constraintId {
            get {
                return this.constraintIdField;
            }
            set {
                if ((object.ReferenceEquals(this.constraintIdField, value) != true)) {
                    this.constraintIdField = value;
                    this.RaisePropertyChanged("constraintId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string constraintValue {
            get {
                return this.constraintValueField;
            }
            set {
                if ((object.ReferenceEquals(this.constraintValueField, value) != true)) {
                    this.constraintValueField = value;
                    this.RaisePropertyChanged("constraintValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ConsoleApplication1.ServiceReferenceRuleSegmentManager.RuleAttributeDataType dataType {
            get {
                return this.dataTypeField;
            }
            set {
                if ((this.dataTypeField.Equals(value) != true)) {
                    this.dataTypeField = value;
                    this.RaisePropertyChanged("dataType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ConsoleApplication1.ServiceReferenceRuleSegmentManager.ConstraintExpression[] expressions {
            get {
                return this.expressionsField;
            }
            set {
                if ((object.ReferenceEquals(this.expressionsField, value) != true)) {
                    this.expressionsField = value;
                    this.RaisePropertyChanged("expressions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int indexNo {
            get {
                return this.indexNoField;
            }
            set {
                if ((this.indexNoField.Equals(value) != true)) {
                    this.indexNoField = value;
                    this.RaisePropertyChanged("indexNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ruleId {
            get {
                return this.ruleIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ruleIdField, value) != true)) {
                    this.ruleIdField = value;
                    this.RaisePropertyChanged("ruleId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RuleType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
        "egmentStudio.Model")]
    public enum RuleType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParentRule = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChildRule = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RuleAttributeDataType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
        "egmentStudio.Model")]
    public enum RuleAttributeDataType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Long = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bool = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Float = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Text = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConstraintExpression", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
        "egmentStudio.Model")]
    [System.SerializableAttribute()]
    public partial class ConstraintExpression : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string attributeIdField;
        
        private string constraintIdField;
        
        private string expressionIdField;
        
        private string expressionValueField;
        
        private int indexNoField;
        
        private string myOperatorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string attributeId {
            get {
                return this.attributeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.attributeIdField, value) != true)) {
                    this.attributeIdField = value;
                    this.RaisePropertyChanged("attributeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string constraintId {
            get {
                return this.constraintIdField;
            }
            set {
                if ((object.ReferenceEquals(this.constraintIdField, value) != true)) {
                    this.constraintIdField = value;
                    this.RaisePropertyChanged("constraintId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string expressionId {
            get {
                return this.expressionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.expressionIdField, value) != true)) {
                    this.expressionIdField = value;
                    this.RaisePropertyChanged("expressionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string expressionValue {
            get {
                return this.expressionValueField;
            }
            set {
                if ((object.ReferenceEquals(this.expressionValueField, value) != true)) {
                    this.expressionValueField = value;
                    this.RaisePropertyChanged("expressionValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int indexNo {
            get {
                return this.indexNoField;
            }
            set {
                if ((this.indexNoField.Equals(value) != true)) {
                    this.indexNoField = value;
                    this.RaisePropertyChanged("indexNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string myOperator {
            get {
                return this.myOperatorField;
            }
            set {
                if ((object.ReferenceEquals(this.myOperatorField, value) != true)) {
                    this.myOperatorField = value;
                    this.RaisePropertyChanged("myOperator");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SegmentFrequency", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
        "egmentStudio.Model")]
    [System.SerializableAttribute()]
    public partial class SegmentFrequency : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string frequencyTypeField;
        
        private string textField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string frequencyType {
            get {
                return this.frequencyTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.frequencyTypeField, value) != true)) {
                    this.frequencyTypeField = value;
                    this.RaisePropertyChanged("frequencyType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string text {
            get {
                return this.textField;
            }
            set {
                if ((object.ReferenceEquals(this.textField, value) != true)) {
                    this.textField = value;
                    this.RaisePropertyChanged("text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SegmentBaseSimple", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
        "egmentStudio.Model")]
    [System.SerializableAttribute()]
    public partial class SegmentBaseSimple : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AuthoringSegmentIdk__BackingFieldField;
        
        private System.DateTime CreateTimek__BackingFieldField;
        
        private string Descriptionk__BackingFieldField;
        
        private System.Nullable<System.DateTime> LastModifiedTimek__BackingFieldField;
        
        private string OwnerIdk__BackingFieldField;
        
        private string SegmentIdk__BackingFieldField;
        
        private string SegmentNamek__BackingFieldField;
        
        private ConsoleApplication1.ServiceReferenceRuleSegmentManager.SegmentType SegmentTypeIdk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<AuthoringSegmentId>k__BackingField", IsRequired=true)]
        public int AuthoringSegmentIdk__BackingField {
            get {
                return this.AuthoringSegmentIdk__BackingFieldField;
            }
            set {
                if ((this.AuthoringSegmentIdk__BackingFieldField.Equals(value) != true)) {
                    this.AuthoringSegmentIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("AuthoringSegmentIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CreateTime>k__BackingField", IsRequired=true)]
        public System.DateTime CreateTimek__BackingField {
            get {
                return this.CreateTimek__BackingFieldField;
            }
            set {
                if ((this.CreateTimek__BackingFieldField.Equals(value) != true)) {
                    this.CreateTimek__BackingFieldField = value;
                    this.RaisePropertyChanged("CreateTimek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Description>k__BackingField", IsRequired=true)]
        public string Descriptionk__BackingField {
            get {
                return this.Descriptionk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Descriptionk__BackingFieldField, value) != true)) {
                    this.Descriptionk__BackingFieldField = value;
                    this.RaisePropertyChanged("Descriptionk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<LastModifiedTime>k__BackingField", IsRequired=true)]
        public System.Nullable<System.DateTime> LastModifiedTimek__BackingField {
            get {
                return this.LastModifiedTimek__BackingFieldField;
            }
            set {
                if ((this.LastModifiedTimek__BackingFieldField.Equals(value) != true)) {
                    this.LastModifiedTimek__BackingFieldField = value;
                    this.RaisePropertyChanged("LastModifiedTimek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<OwnerId>k__BackingField", IsRequired=true)]
        public string OwnerIdk__BackingField {
            get {
                return this.OwnerIdk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerIdk__BackingFieldField, value) != true)) {
                    this.OwnerIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("OwnerIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SegmentId>k__BackingField", IsRequired=true)]
        public string SegmentIdk__BackingField {
            get {
                return this.SegmentIdk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.SegmentIdk__BackingFieldField, value) != true)) {
                    this.SegmentIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("SegmentIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SegmentName>k__BackingField", IsRequired=true)]
        public string SegmentNamek__BackingField {
            get {
                return this.SegmentNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.SegmentNamek__BackingFieldField, value) != true)) {
                    this.SegmentNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("SegmentNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SegmentTypeId>k__BackingField", IsRequired=true)]
        public ConsoleApplication1.ServiceReferenceRuleSegmentManager.SegmentType SegmentTypeIdk__BackingField {
            get {
                return this.SegmentTypeIdk__BackingFieldField;
            }
            set {
                if ((this.SegmentTypeIdk__BackingFieldField.Equals(value) != true)) {
                    this.SegmentTypeIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("SegmentTypeIdk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessCode", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
        "egmentStudio.Model")]
    public enum AccessCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoAccess = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Explore = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Read = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Copy = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Owned = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScoreResultAggregate", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.AudienceIntelligenc" +
        "eService.FastScoringService")]
    [System.SerializableAttribute()]
    public partial class ScoreResultAggregate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReferenceRuleSegmentManager.UserAgeAggregate[] UserAgeAggregatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReferenceRuleSegmentManager.UserGenderAggregate[] UserGenderAggregatesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.ServiceReferenceRuleSegmentManager.UserAgeAggregate[] UserAgeAggregates {
            get {
                return this.UserAgeAggregatesField;
            }
            set {
                if ((object.ReferenceEquals(this.UserAgeAggregatesField, value) != true)) {
                    this.UserAgeAggregatesField = value;
                    this.RaisePropertyChanged("UserAgeAggregates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.ServiceReferenceRuleSegmentManager.UserGenderAggregate[] UserGenderAggregates {
            get {
                return this.UserGenderAggregatesField;
            }
            set {
                if ((object.ReferenceEquals(this.UserGenderAggregatesField, value) != true)) {
                    this.UserGenderAggregatesField = value;
                    this.RaisePropertyChanged("UserGenderAggregates");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAgeAggregate", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.AudienceIntelligenc" +
        "eService.FastScoringService")]
    [System.SerializableAttribute()]
    public partial class UserAgeAggregate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short MaxAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short MinAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short MaxAge {
            get {
                return this.MaxAgeField;
            }
            set {
                if ((this.MaxAgeField.Equals(value) != true)) {
                    this.MaxAgeField = value;
                    this.RaisePropertyChanged("MaxAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short MinAge {
            get {
                return this.MinAgeField;
            }
            set {
                if ((this.MinAgeField.Equals(value) != true)) {
                    this.MinAgeField = value;
                    this.RaisePropertyChanged("MinAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserCount {
            get {
                return this.UserCountField;
            }
            set {
                if ((this.UserCountField.Equals(value) != true)) {
                    this.UserCountField = value;
                    this.RaisePropertyChanged("UserCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserGenderAggregate", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.AudienceIntelligenc" +
        "eService.FastScoringService")]
    [System.SerializableAttribute()]
    public partial class UserGenderAggregate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserCount {
            get {
                return this.UserCountField;
            }
            set {
                if ((this.UserCountField.Equals(value) != true)) {
                    this.UserCountField = value;
                    this.RaisePropertyChanged("UserCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
        "egmentStudio.Exception")]
    [System.SerializableAttribute()]
    public partial class ServerFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeBaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExceptionNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReferenceRuleSegmentManager.ExceptionType ExceptionTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Actor {
            get {
                return this.ActorField;
            }
            set {
                if ((object.ReferenceEquals(this.ActorField, value) != true)) {
                    this.ActorField = value;
                    this.RaisePropertyChanged("Actor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeBase {
            get {
                return this.CodeBaseField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeBaseField, value) != true)) {
                    this.CodeBaseField = value;
                    this.RaisePropertyChanged("CodeBase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomMessage {
            get {
                return this.CustomMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomMessageField, value) != true)) {
                    this.CustomMessageField = value;
                    this.RaisePropertyChanged("CustomMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomSource {
            get {
                return this.CustomSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomSourceField, value) != true)) {
                    this.CustomSourceField = value;
                    this.RaisePropertyChanged("CustomSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExceptionNumber {
            get {
                return this.ExceptionNumberField;
            }
            set {
                if ((this.ExceptionNumberField.Equals(value) != true)) {
                    this.ExceptionNumberField = value;
                    this.RaisePropertyChanged("ExceptionNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.ServiceReferenceRuleSegmentManager.ExceptionType ExceptionType {
            get {
                return this.ExceptionTypeField;
            }
            set {
                if ((this.ExceptionTypeField.Equals(value) != true)) {
                    this.ExceptionTypeField = value;
                    this.RaisePropertyChanged("ExceptionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
        "egmentStudio.Exception")]
    public enum ExceptionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserException = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AppException = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SysException = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceRuleSegmentManager.IRuleSegment", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    public interface IRuleSegment {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/PublishSegment", ReplyAction="http://tempuri.org/IRuleSegment/PublishSegmentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/PublishSegmentServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        bool PublishSegment(string segmentId, System.Nullable<double> clientMinuteTimeZoneOffset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/GetSegmentTypeById", ReplyAction="http://tempuri.org/IRuleSegment/GetSegmentTypeByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/GetSegmentTypeByIdServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        ConsoleApplication1.ServiceReferenceRuleSegmentManager.SegmentType GetSegmentTypeById(string segmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/Add", ReplyAction="http://tempuri.org/IRuleSegment/AddResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/AddServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        bool Add(ConsoleApplication1.ServiceReferenceRuleSegmentManager.RuleSegment segment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/Delete", ReplyAction="http://tempuri.org/IRuleSegment/DeleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/DeleteServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        string Delete(string segmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/GetAllFrequencyTypeModel", ReplyAction="http://tempuri.org/IRuleSegment/GetAllFrequencyTypeModelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/GetAllFrequencyTypeModelServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        ConsoleApplication1.ServiceReferenceRuleSegmentManager.SegmentFrequency[] GetAllFrequencyTypeModel();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/GetAllSegments", ReplyAction="http://tempuri.org/IRuleSegment/GetAllSegmentsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/GetAllSegmentsServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        System.Data.DataTable GetAllSegments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/GetById", ReplyAction="http://tempuri.org/IRuleSegment/GetByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/GetByIdServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        ConsoleApplication1.ServiceReferenceRuleSegmentManager.RuleSegment GetById(string segmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/GetSegmentBaseSimpleById", ReplyAction="http://tempuri.org/IRuleSegment/GetSegmentBaseSimpleByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/GetSegmentBaseSimpleByIdServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        ConsoleApplication1.ServiceReferenceRuleSegmentManager.SegmentBaseSimple GetSegmentBaseSimpleById(string segmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/GetExpirationTime", ReplyAction="http://tempuri.org/IRuleSegment/GetExpirationTimeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/GetExpirationTimeServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        string GetExpirationTime(string segmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/UpdatePublishStatus", ReplyAction="http://tempuri.org/IRuleSegment/UpdatePublishStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/UpdatePublishStatusServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        int UpdatePublishStatus(string segmentId, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/GetDataTableById", ReplyAction="http://tempuri.org/IRuleSegment/GetDataTableByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/GetDataTableByIdServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        System.Data.DataTable GetDataTableById(string segmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/GetExportString", ReplyAction="http://tempuri.org/IRuleSegment/GetExportStringResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/GetExportStringServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        string GetExportString(out bool isError, string segmentId, System.Nullable<double> clientMinuteTimeZoneOffset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/GetExportStringWithoughValidation", ReplyAction="http://tempuri.org/IRuleSegment/GetExportStringWithoughValidationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/GetExportStringWithoughValidationServerFaultFault" +
            "", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        string GetExportStringWithoughValidation(string segmentId, System.Nullable<double> clientMinuteTimeZoneOffset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/GetExportStringArray", ReplyAction="http://tempuri.org/IRuleSegment/GetExportStringArrayResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/GetExportStringArrayServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        string GetExportStringArray(string[] segmentId, System.Nullable<double> clientMinuteTimeZoneOffset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/GetOwnerAndSharedInSegments", ReplyAction="http://tempuri.org/IRuleSegment/GetOwnerAndSharedInSegmentsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/GetOwnerAndSharedInSegmentsServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        System.Data.DataTable GetOwnerAndSharedInSegments(string ownerId, string projectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/GetPublishedSegments", ReplyAction="http://tempuri.org/IRuleSegment/GetPublishedSegmentsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/GetPublishedSegmentsServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        System.Data.DataTable GetPublishedSegments(string solutionId, string projectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/GetSegmentsByProjectId", ReplyAction="http://tempuri.org/IRuleSegment/GetSegmentsByProjectIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/GetSegmentsByProjectIdServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        System.Data.DataTable GetSegmentsByProjectId(string projectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/GetSegmentsForPageSharedOutStatus", ReplyAction="http://tempuri.org/IRuleSegment/GetSegmentsForPageSharedOutStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/GetSegmentsForPageSharedOutStatusServerFaultFault" +
            "", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        System.Data.DataTable GetSegmentsForPageSharedOutStatus(string currentOwnerId, string projectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/GetSegmentsForPageSharedOutUpdate", ReplyAction="http://tempuri.org/IRuleSegment/GetSegmentsForPageSharedOutUpdateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/GetSegmentsForPageSharedOutUpdateServerFaultFault" +
            "", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        System.Data.DataTable GetSegmentsForPageSharedOutUpdate(string ownerId, string shareOutTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/GetSharedInSegments", ReplyAction="http://tempuri.org/IRuleSegment/GetSharedInSegmentsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/GetSharedInSegmentsServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        System.Data.DataTable GetSharedInSegments(string currentOwnerId, string projectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/IsIncludeDerivedAttributeInSegment", ReplyAction="http://tempuri.org/IRuleSegment/IsIncludeDerivedAttributeInSegmentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/IsIncludeDerivedAttributeInSegmentServerFaultFaul" +
            "t", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        bool IsIncludeDerivedAttributeInSegment(string segmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/IsXmlFormatWell", ReplyAction="http://tempuri.org/IRuleSegment/IsXmlFormatWellResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/IsXmlFormatWellServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        bool IsXmlFormatWell(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/ShareInSegment", ReplyAction="http://tempuri.org/IRuleSegment/ShareInSegmentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/ShareInSegmentServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        bool ShareInSegment(string segmentId, ConsoleApplication1.ServiceReferenceRuleSegmentManager.AccessCode accessCode, string shareInUser, string projectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/ShareOutSegment", ReplyAction="http://tempuri.org/IRuleSegment/ShareOutSegmentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/ShareOutSegmentServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        bool ShareOutSegment(string segmentId, string userId, ConsoleApplication1.ServiceReferenceRuleSegmentManager.AccessCode accessCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/Update", ReplyAction="http://tempuri.org/IRuleSegment/UpdateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/UpdateServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        bool Update(ConsoleApplication1.ServiceReferenceRuleSegmentManager.RuleSegment segment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/GetNewSegmentNameForSaveAs", ReplyAction="http://tempuri.org/IRuleSegment/GetNewSegmentNameForSaveAsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/GetNewSegmentNameForSaveAsServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        string GetNewSegmentNameForSaveAs(string oldSegmentName, string currentOwnerId, string segmentOwnerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/ValidateSingleSegment", ReplyAction="http://tempuri.org/IRuleSegment/ValidateSingleSegmentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/ValidateSingleSegmentServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        bool ValidateSingleSegment(ConsoleApplication1.ServiceReferenceRuleSegmentManager.SegmentBase segment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/GetValidateDetail", ReplyAction="http://tempuri.org/IRuleSegment/GetValidateDetailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/GetValidateDetailServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        string GetValidateDetail(string entityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/SwapAuthoringSegmentIds", ReplyAction="http://tempuri.org/IRuleSegment/SwapAuthoringSegmentIdsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/SwapAuthoringSegmentIdsServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        string SwapAuthoringSegmentIds(string segmentIdFirst, string segmentIdSecond);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/GetSegmentIdByScoringJobId", ReplyAction="http://tempuri.org/IRuleSegment/GetSegmentIdByScoringJobIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/GetSegmentIdByScoringJobIdServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        string GetSegmentIdByScoringJobId(string scoringJobId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/FastScoreSegment", ReplyAction="http://tempuri.org/IRuleSegment/FastScoreSegmentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/FastScoreSegmentServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        bool FastScoreSegment(string segmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/FastScoreResultAggregate", ReplyAction="http://tempuri.org/IRuleSegment/FastScoreResultAggregateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/FastScoreResultAggregateServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        ConsoleApplication1.ServiceReferenceRuleSegmentManager.ScoreResultAggregate FastScoreResultAggregate(string segmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/GetSegmentPropertyPack", ReplyAction="http://tempuri.org/IRuleSegment/GetSegmentPropertyPackResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/GetSegmentPropertyPackServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        System.Collections.Generic.Dictionary<string, string> GetSegmentPropertyPack(string segmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/AddSegmentPropertyPackProperty", ReplyAction="http://tempuri.org/IRuleSegment/AddSegmentPropertyPackPropertyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/AddSegmentPropertyPackPropertyServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        void AddSegmentPropertyPackProperty(string segmentId, string key, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleSegment/ExportSegmentPack", ReplyAction="http://tempuri.org/IRuleSegment/ExportSegmentPackResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReferenceRuleSegmentManager.ServerFault), Action="http://tempuri.org/IRuleSegment/ExportSegmentPackServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        string ExportSegmentPack(string segmentId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRuleSegmentChannel : ConsoleApplication1.ServiceReferenceRuleSegmentManager.IRuleSegment, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RuleSegmentClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReferenceRuleSegmentManager.IRuleSegment>, ConsoleApplication1.ServiceReferenceRuleSegmentManager.IRuleSegment {
        
        public RuleSegmentClient() {
        }
        
        public RuleSegmentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RuleSegmentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RuleSegmentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RuleSegmentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool PublishSegment(string segmentId, System.Nullable<double> clientMinuteTimeZoneOffset) {
            return base.Channel.PublishSegment(segmentId, clientMinuteTimeZoneOffset);
        }
        
        public ConsoleApplication1.ServiceReferenceRuleSegmentManager.SegmentType GetSegmentTypeById(string segmentId) {
            return base.Channel.GetSegmentTypeById(segmentId);
        }
        
        public bool Add(ConsoleApplication1.ServiceReferenceRuleSegmentManager.RuleSegment segment) {
            return base.Channel.Add(segment);
        }
        
        public string Delete(string segmentId) {
            return base.Channel.Delete(segmentId);
        }
        
        public ConsoleApplication1.ServiceReferenceRuleSegmentManager.SegmentFrequency[] GetAllFrequencyTypeModel() {
            return base.Channel.GetAllFrequencyTypeModel();
        }
        
        public System.Data.DataTable GetAllSegments() {
            return base.Channel.GetAllSegments();
        }
        
        public ConsoleApplication1.ServiceReferenceRuleSegmentManager.RuleSegment GetById(string segmentId) {
            return base.Channel.GetById(segmentId);
        }
        
        public ConsoleApplication1.ServiceReferenceRuleSegmentManager.SegmentBaseSimple GetSegmentBaseSimpleById(string segmentId) {
            return base.Channel.GetSegmentBaseSimpleById(segmentId);
        }
        
        public string GetExpirationTime(string segmentId) {
            return base.Channel.GetExpirationTime(segmentId);
        }
        
        public int UpdatePublishStatus(string segmentId, int status) {
            return base.Channel.UpdatePublishStatus(segmentId, status);
        }
        
        public System.Data.DataTable GetDataTableById(string segmentId) {
            return base.Channel.GetDataTableById(segmentId);
        }
        
        public string GetExportString(out bool isError, string segmentId, System.Nullable<double> clientMinuteTimeZoneOffset) {
            return base.Channel.GetExportString(out isError, segmentId, clientMinuteTimeZoneOffset);
        }
        
        public string GetExportStringWithoughValidation(string segmentId, System.Nullable<double> clientMinuteTimeZoneOffset) {
            return base.Channel.GetExportStringWithoughValidation(segmentId, clientMinuteTimeZoneOffset);
        }
        
        public string GetExportStringArray(string[] segmentId, System.Nullable<double> clientMinuteTimeZoneOffset) {
            return base.Channel.GetExportStringArray(segmentId, clientMinuteTimeZoneOffset);
        }
        
        public System.Data.DataTable GetOwnerAndSharedInSegments(string ownerId, string projectId) {
            return base.Channel.GetOwnerAndSharedInSegments(ownerId, projectId);
        }
        
        public System.Data.DataTable GetPublishedSegments(string solutionId, string projectId) {
            return base.Channel.GetPublishedSegments(solutionId, projectId);
        }
        
        public System.Data.DataTable GetSegmentsByProjectId(string projectId) {
            return base.Channel.GetSegmentsByProjectId(projectId);
        }
        
        public System.Data.DataTable GetSegmentsForPageSharedOutStatus(string currentOwnerId, string projectId) {
            return base.Channel.GetSegmentsForPageSharedOutStatus(currentOwnerId, projectId);
        }
        
        public System.Data.DataTable GetSegmentsForPageSharedOutUpdate(string ownerId, string shareOutTo) {
            return base.Channel.GetSegmentsForPageSharedOutUpdate(ownerId, shareOutTo);
        }
        
        public System.Data.DataTable GetSharedInSegments(string currentOwnerId, string projectId) {
            return base.Channel.GetSharedInSegments(currentOwnerId, projectId);
        }
        
        public bool IsIncludeDerivedAttributeInSegment(string segmentId) {
            return base.Channel.IsIncludeDerivedAttributeInSegment(segmentId);
        }
        
        public bool IsXmlFormatWell(string xml) {
            return base.Channel.IsXmlFormatWell(xml);
        }
        
        public bool ShareInSegment(string segmentId, ConsoleApplication1.ServiceReferenceRuleSegmentManager.AccessCode accessCode, string shareInUser, string projectId) {
            return base.Channel.ShareInSegment(segmentId, accessCode, shareInUser, projectId);
        }
        
        public bool ShareOutSegment(string segmentId, string userId, ConsoleApplication1.ServiceReferenceRuleSegmentManager.AccessCode accessCode) {
            return base.Channel.ShareOutSegment(segmentId, userId, accessCode);
        }
        
        public bool Update(ConsoleApplication1.ServiceReferenceRuleSegmentManager.RuleSegment segment) {
            return base.Channel.Update(segment);
        }
        
        public string GetNewSegmentNameForSaveAs(string oldSegmentName, string currentOwnerId, string segmentOwnerId) {
            return base.Channel.GetNewSegmentNameForSaveAs(oldSegmentName, currentOwnerId, segmentOwnerId);
        }
        
        public bool ValidateSingleSegment(ConsoleApplication1.ServiceReferenceRuleSegmentManager.SegmentBase segment) {
            return base.Channel.ValidateSingleSegment(segment);
        }
        
        public string GetValidateDetail(string entityId) {
            return base.Channel.GetValidateDetail(entityId);
        }
        
        public string SwapAuthoringSegmentIds(string segmentIdFirst, string segmentIdSecond) {
            return base.Channel.SwapAuthoringSegmentIds(segmentIdFirst, segmentIdSecond);
        }
        
        public string GetSegmentIdByScoringJobId(string scoringJobId) {
            return base.Channel.GetSegmentIdByScoringJobId(scoringJobId);
        }
        
        public bool FastScoreSegment(string segmentId) {
            return base.Channel.FastScoreSegment(segmentId);
        }
        
        public ConsoleApplication1.ServiceReferenceRuleSegmentManager.ScoreResultAggregate FastScoreResultAggregate(string segmentId) {
            return base.Channel.FastScoreResultAggregate(segmentId);
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetSegmentPropertyPack(string segmentId) {
            return base.Channel.GetSegmentPropertyPack(segmentId);
        }
        
        public void AddSegmentPropertyPackProperty(string segmentId, string key, string value) {
            base.Channel.AddSegmentPropertyPackProperty(segmentId, key, value);
        }
        
        public string ExportSegmentPack(string segmentId) {
            return base.Channel.ExportSegmentPack(segmentId);
        }
    }
}
