//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.UserManager {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
        "egmentStudio.Model")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int attributeQuotaField;
        
        private string emailField;
        
        private string encryptedpasswordField;
        
        private int segmentQuotaField;
        
        private bool statusField;
        
        private string userIdField;
        
        private ConsoleApplication1.UserManager.UserProfile userProfileModelField;
        
        private ConsoleApplication1.UserManager.UserType userTypeField;
        
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int attributeQuota {
            get {
                return this.attributeQuotaField;
            }
            set {
                if ((this.attributeQuotaField.Equals(value) != true)) {
                    this.attributeQuotaField = value;
                    this.RaisePropertyChanged("attributeQuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string encryptedpassword {
            get {
                return this.encryptedpasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.encryptedpasswordField, value) != true)) {
                    this.encryptedpasswordField = value;
                    this.RaisePropertyChanged("encryptedpassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int segmentQuota {
            get {
                return this.segmentQuotaField;
            }
            set {
                if ((this.segmentQuotaField.Equals(value) != true)) {
                    this.segmentQuotaField = value;
                    this.RaisePropertyChanged("segmentQuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                if ((object.ReferenceEquals(this.userIdField, value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ConsoleApplication1.UserManager.UserProfile userProfileModel {
            get {
                return this.userProfileModelField;
            }
            set {
                if ((object.ReferenceEquals(this.userProfileModelField, value) != true)) {
                    this.userProfileModelField = value;
                    this.RaisePropertyChanged("userProfileModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ConsoleApplication1.UserManager.UserType userType {
            get {
                return this.userTypeField;
            }
            set {
                if ((this.userTypeField.Equals(value) != true)) {
                    this.userTypeField = value;
                    this.RaisePropertyChanged("userType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
        "egmentStudio.Model")]
    [System.SerializableAttribute()]
    public partial class UserProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string defaultSolutionIdField;
        
        private string userIdField;
        
        private ConsoleApplication1.UserManager.UserSolutionModel[] userSolutionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string defaultSolutionId {
            get {
                return this.defaultSolutionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.defaultSolutionIdField, value) != true)) {
                    this.defaultSolutionIdField = value;
                    this.RaisePropertyChanged("defaultSolutionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                if ((object.ReferenceEquals(this.userIdField, value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ConsoleApplication1.UserManager.UserSolutionModel[] userSolutions {
            get {
                return this.userSolutionsField;
            }
            set {
                if ((object.ReferenceEquals(this.userSolutionsField, value) != true)) {
                    this.userSolutionsField = value;
                    this.RaisePropertyChanged("userSolutions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
        "egmentStudio.Model")]
    public enum UserType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SegmentManager = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Administrator = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IntermediateUser = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BasicUser = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SegmentInsightUser = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSolutionModel", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
        "egmentStudio.Model")]
    [System.SerializableAttribute()]
    public partial class UserSolutionModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string defaultProjectIdField;
        
        private string idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string defaultProjectId {
            get {
                return this.defaultProjectIdField;
            }
            set {
                if ((object.ReferenceEquals(this.defaultProjectIdField, value) != true)) {
                    this.defaultProjectIdField = value;
                    this.RaisePropertyChanged("defaultProjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
        "egmentStudio.Exception")]
    [System.SerializableAttribute()]
    public partial class ServerFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeBaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExceptionNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.UserManager.ExceptionType ExceptionTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Actor {
            get {
                return this.ActorField;
            }
            set {
                if ((object.ReferenceEquals(this.ActorField, value) != true)) {
                    this.ActorField = value;
                    this.RaisePropertyChanged("Actor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeBase {
            get {
                return this.CodeBaseField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeBaseField, value) != true)) {
                    this.CodeBaseField = value;
                    this.RaisePropertyChanged("CodeBase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomMessage {
            get {
                return this.CustomMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomMessageField, value) != true)) {
                    this.CustomMessageField = value;
                    this.RaisePropertyChanged("CustomMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomSource {
            get {
                return this.CustomSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomSourceField, value) != true)) {
                    this.CustomSourceField = value;
                    this.RaisePropertyChanged("CustomSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExceptionNumber {
            get {
                return this.ExceptionNumberField;
            }
            set {
                if ((this.ExceptionNumberField.Equals(value) != true)) {
                    this.ExceptionNumberField = value;
                    this.RaisePropertyChanged("ExceptionNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.UserManager.ExceptionType ExceptionType {
            get {
                return this.ExceptionTypeField;
            }
            set {
                if ((this.ExceptionTypeField.Equals(value) != true)) {
                    this.ExceptionTypeField = value;
                    this.RaisePropertyChanged("ExceptionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
        "egmentStudio.Exception")]
    public enum ExceptionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserException = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AppException = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SysException = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserManager.IUser", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    public interface IUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/AddUser", ReplyAction="http://tempuri.org/IUser/AddUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.UserManager.ServerFault), Action="http://tempuri.org/IUser/AddUserServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        bool AddUser(ConsoleApplication1.UserManager.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/Delete", ReplyAction="http://tempuri.org/IUser/DeleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.UserManager.ServerFault), Action="http://tempuri.org/IUser/DeleteServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        string Delete(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetList", ReplyAction="http://tempuri.org/IUser/GetListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.UserManager.ServerFault), Action="http://tempuri.org/IUser/GetListServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        ConsoleApplication1.UserManager.User[] GetList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetUserById", ReplyAction="http://tempuri.org/IUser/GetUserByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.UserManager.ServerFault), Action="http://tempuri.org/IUser/GetUserByIdServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        ConsoleApplication1.UserManager.User GetUserById(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/Remove", ReplyAction="http://tempuri.org/IUser/RemoveResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.UserManager.ServerFault), Action="http://tempuri.org/IUser/RemoveServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        bool Remove(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/UpdatePassword", ReplyAction="http://tempuri.org/IUser/UpdatePasswordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.UserManager.ServerFault), Action="http://tempuri.org/IUser/UpdatePasswordServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        bool UpdatePassword(string userId, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/UpdateUser", ReplyAction="http://tempuri.org/IUser/UpdateUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.UserManager.ServerFault), Action="http://tempuri.org/IUser/UpdateUserServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        bool UpdateUser(string userId, ConsoleApplication1.UserManager.UserType userType, int segmentQuota, int attributeQuota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/UpdateUserProfile", ReplyAction="http://tempuri.org/IUser/UpdateUserProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.UserManager.ServerFault), Action="http://tempuri.org/IUser/UpdateUserProfileServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        bool UpdateUserProfile(ConsoleApplication1.UserManager.UserProfile userProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/UpdateUserMailAddress", ReplyAction="http://tempuri.org/IUser/UpdateUserMailAddressResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.UserManager.ServerFault), Action="http://tempuri.org/IUser/UpdateUserMailAddressServerFaultFault", Name="ServerFault", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Advertising.BehaviorTargeting.S" +
            "egmentStudio.Exception")]
        bool UpdateUserMailAddress(string userId, string newAddress);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserChannel : ConsoleApplication1.UserManager.IUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserClient : System.ServiceModel.ClientBase<ConsoleApplication1.UserManager.IUser>, ConsoleApplication1.UserManager.IUser {
        
        public UserClient() {
        }
        
        public UserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddUser(ConsoleApplication1.UserManager.User user) {
            return base.Channel.AddUser(user);
        }
        
        public string Delete(string userId) {
            return base.Channel.Delete(userId);
        }
        
        public ConsoleApplication1.UserManager.User[] GetList() {
            return base.Channel.GetList();
        }
        
        public ConsoleApplication1.UserManager.User GetUserById(string userId) {
            return base.Channel.GetUserById(userId);
        }
        
        public bool Remove(string userId) {
            return base.Channel.Remove(userId);
        }
        
        public bool UpdatePassword(string userId, string password) {
            return base.Channel.UpdatePassword(userId, password);
        }
        
        public bool UpdateUser(string userId, ConsoleApplication1.UserManager.UserType userType, int segmentQuota, int attributeQuota) {
            return base.Channel.UpdateUser(userId, userType, segmentQuota, attributeQuota);
        }
        
        public bool UpdateUserProfile(ConsoleApplication1.UserManager.UserProfile userProfile) {
            return base.Channel.UpdateUserProfile(userProfile);
        }
        
        public bool UpdateUserMailAddress(string userId, string newAddress) {
            return base.Channel.UpdateUserMailAddress(userId, newAddress);
        }
    }
}
